version: 2
jobs:
  build:
    working_directory: ~/repo
    shell: /bin/bash -eo pipefail
    docker:
      - image: vsiri/circleci:bash-compose-lfs
    steps:
      - checkout

      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init --recursive

      - setup_remote_docker

      - run:
          name: Smuggle repo to remote docker
          command: tar zc --exclude .git . | docker run -i -v /root/repo:/repo -w /repo alpine:3.6 tar zx

      - run:
          name: Build VK_METRICS docker
          command: |
            source setup.env
            just docker build

      - run:
          name: Build VK_METRICS code
          no_output_timeout: 30m
          command: |
            source setup.env
            just compile

      - run:
          name: Running test code
          no_output_timeout: 30m
          command: |
            source setup.env
            just test
