version: '2.3'
services:

  compiler:
    build:
      context: .
      dockerfile: docker/compiler.Dockerfile

    # prevent clobbering images from other users
    image: ${VKM_DOCKER_REPO}:compiler_${VKM_USERNAME}

    environment:
      - DOCKER_UID=${VKM_UID}
      - DOCKER_GIDS=${VKM_GIDS}
      - DOCKER_GROUP_NAMES=${VKM_GROUP_NAMES}
      - DOCKER_USERNAME=${VKM_USERNAME_DOCKER}
      - DOCKER_HOME=${VKM_HOME_DOCKER}

    volumes:
      - ${VKM_SOURCE_DIR}:${VKM_SOURCE_DIR_DOCKER}:ro
      - ${VKM_BUILD_DIR}:${VKM_BUILD_DIR_DOCKER}
      - ${VKM_INSTALL_DIR}:${VKM_INSTALL_DIR_DOCKER}

  vkm:
    build:
      context: .
      dockerfile: docker/vkm.Dockerfile

    # prevent clobbering images from other users
    image: ${VKM_DOCKER_REPO}:vkm_${VKM_USERNAME}

    environment:
      - DOCKER_UID=${VKM_UID}
      - DOCKER_GIDS=${VKM_GIDS}
      - DOCKER_GROUP_NAMES=${VKM_GROUP_NAMES}
      - DOCKER_USERNAME=${VKM_USERNAME_DOCKER}
      - DOCKER_HOME=${VKM_HOME_DOCKER}

    volumes:
      - ${VKM_SOURCE_DIR}:${VKM_SOURCE_DIR_DOCKER}:ro
      - ${VKM_INSTALL_DIR}:${VKM_INSTALL_DIR_DOCKER}
      - ${VKM_VENV_DIR}:${VKM_VENV_DIR_DOCKER}

volumes:
  vkm-bin:
  vkm-build:
  vkm-venv: