version: 2
jobs:
  build:
    working_directory: ~/repo
    shell: /bin/bash -eo pipefail
    docker:
      - image: vsiri/circleci:bash-compose-lfs
    steps:

      - checkout

      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init --recursive

      - run:
          name: Additional setup
          command: |
            touch local.env local_post.env
            sed -i -e 's/group_names/id -G -n/g' vkm.env

      - setup_remote_docker

      - run:
          name: Install JUST
          command: |
            apk update
            apk add util-linux
            wget -O /usr/local/bin/just https://github.com/VisionSystemsInc/just/releases/download/0.0.7/just-Linux-x86_64
            chmod 755 /usr/local/bin/just
            just --version

      - run:
          name: Smuggle repo to remote docker
          command: tar zc --exclude .git . | docker run -i -v /root/repo:/repo -w /repo alpine:3.6 tar zx

      - run:
          name: Build all dockers
          command: just build

      - run:
          name: Compile source code
          command: just compile

      - run:
          name: Tests
          command: just test
