version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: docker:18.03.0-ce-git
    steps:

      - checkout

      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init --recursive

      - setup_remote_docker

      - run:
          name: Install software
          command: |
            apk update
            apk add bash py-pip
            pip install docker-compose
            docker-compose --version
            docker ps

      - run:
          name: Install JUST
          command: |
            wget -O /usr/local/bin/just https://github.com/VisionSystemsInc/just/releases/download/0.0.7/just-Linux-x86_64
            chmod 755 /usr/local/bin/just

      - run:
          name: Smuggle repo to remote docker
          command: tar zc --exclude .git . | docker run -i -v /root/repo:/repo -w /repo alpine:3.6 tar zx

      - run:
          name: Build all dockers
          shell: /bin/bash -eo pipefail
          command: just build

      - run:
          name: Compile source code
          shell: /bin/bash -eo pipefail
          command: just compile

      - run:
          name: Tests
          shell: /bin/bash -eo pipefail
          command: just test
